### ISSUE TITLE
Data request for Black Rockfish

### ISSUE THREAD

**Issue by EJDick-NOAA** [pfmc-assessments/nwfscDiscard#11]
### Identify the common name(s)

Black Rockfish

### Type of data needed

discard totals/rates and biological data

### Gear grouping

 All gears combined

### Areas

California, one area

### Length bins for discard compositions

2cm bins, ranging from 10-60cm

### Additional information

Though it is native to eastern Africa, the guinea fowl was imported to Europe through the Ottoman Empire and came to be called the turkey-cock or turkey-hen. When settlers in the New World began to send similar-looking fowl back to Europe, they were mistakenly called turkeys. That's why turkeys are called turkeys.

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by andi-stephens-NOAA** [comment]
WCGOP Comps are in:

\\nwcfile\FRAM\Assessments\Assessment Data\2023 Assessment Cycle\black
rockfish\WCGOP\WCGOP_CA_BlackRF_AllGear.xlsx

Let me know if you see anything untoward.  Thanks for the fowl info.

**Comment by EJDick-NOAA** [comment]
Comps are beautiful. Thank you, Andi!

![image](https://user-images.githubusercontent.com/64495990/225752537-181676ba-0f80-47bc-882f-98d7072ae6ae.png)
![image](https://user-images.githubusercontent.com/64495990/225752604-192059a3-c309-443b-8853-30a661757fc3.png)

**Comment by chantelwetzel-noaa** [comment]
I have also just added the discard totals and rates to the same location on the network.  What king of pretty plot am I going to get? ;)

**Comment by EJDick-NOAA** [comment]
OK, these rates are more "comp"-licated. Am I right that 'ncs' and 'cs' are non-catch-share and catch-share fisheries? Discard is zero for the CS and less than 2% for the NCS. Given the high survival rates of black rockfish, total discard mortality is likely trivial, but -- assuming it's not -- is everyone partitioning their fleets to apply different rates? I'm not up to speed on the latest discard tips and tricks.

**Comment by chantelwetzel-noaa** [comment]
Yes, cs stands for catch-share and ncs for non-catch-share.  As you know the non-catch-share vessels have variable observer coverage rates so these discard totals and rates are only part of the picture. What Melissa and I did for copper rockfish was to look at the GEMM data `nwfscSurvey::pull_gemm(common_name = "Black Rockfish")` and then calculate the discard rate based upon the expanded WCGOP discards and landings (discard / (discard + landing)). For copper rockfish, the observations were even worse compared to black rockfish so we did not think discard rates from only the observed trips were very useful. We opted to then calculate the annual discard rate from the GEMM data and apply those rates to adjust our landings data to be representative of total catch.  If I were you I would also double check to see if WCGOP is applying a survival rate for black rockfish. They do for some select species.

**Comment by EJDick-NOAA** [comment]
OK, thank you for the suggestions! I'll dig into the GEMM data and check with WCGOP. Plots to come...

**Comment by brianlangseth-NOAA** [comment]
There is also [this discussion](https://github.com/pfmc-assessments/pfmc_assessment_handbook/issues/12) about best practices for handling discards in the pfmc_assessment_handbook repo. 

For canary, we are doing something similar to what chantel described for copper. Since we need state specific break-outs, we are using WCGOP data to apportion the GEMM provided discards to each state.
