### ISSUE TITLE
Data request for Rex sole (Glyptocephalus zachirus) - COASTWIDE

### ISSUE THREAD

**Issue by somros** [pfmc-assessments/nwfscDiscard#12]
### Identify the common name(s)

PACFIN Codes: "REX" "REX1"
PACFIN Common names: "REX SOLE" "NOM. REX SOLE"

### Type of data needed

discard totals/rates and biological data

### Gear grouping

Trawl gear (all trawl gear types aggregated)

### Areas

Coastwide

### Length bins for discard compositions

Min: 2 cm
Max: 60 cm
Bin size: 2 cm

### Additional information

For model bridging purposes from the 2013 rex sole assessment we need to explore coastwide discard rates and biological data. The end goal is to use the N-S rates as we originally requested, but to bridge the models it seems we will need to present a coastwide version and then explore sensitivities to the split.

We request the data as part of the Applied Stock Assessment class (FISH 576) at UW. 

Please reach out to [alberto.rovellini@noaa.gov](mailto:alberto.rovellini@noaa.gov) if I omitted any necessary information.

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
@okenk @gertsevv @melissahaltuch-NOAA I have processed the discard rates and have put them on the network.

**Comment by okenk** [comment]
Thanks-- these can be emailed, right?

**Comment by chantelwetzel-noaa** [comment]
Yes, because they are summarized in a manner that they are no longer confidential.  Thank you for checking.

**Comment by andi-stephens-NOAA** [comment]
Bio comps for all gears combined, coastwide are on the network.

Let me know if you have any questions.

**Comment by okenk** [comment]
The data request was for a minimum length bin of 2 cm. However, it appears as though the minimum length bin is 12 cm. This is leading to a bimodal distribution of discard lengths (top left panel). Could we get an updated comp data matching the requested specifications for both this data request and also #7. Thank you!

![image](https://user-images.githubusercontent.com/205013/233229739-3ecced32-be57-4eb6-90bb-bf79fb1c77c0.png)

**Comment by chantelwetzel-noaa** [comment]
@andi-stephens-NOAA

**Comment by chantelwetzel-noaa** [comment]
@okenk @andi-stephens-NOAA Has the data request been filled yet?  If so, I would like to close this request.

**Comment by okenk** [comment]
No, it has not.

**Comment by andi-stephens-NOAA** [comment]
Hi Kiva,

    I've been out sick -- I had minor surgery last Wednesday -- and didn't
see this.  I'll get those to you later today.

--Andi

**Comment by andi-stephens-NOAA** [comment]
Two new files:

NEW_Rex_WCGOP_Coastwide.xlsx
NEW_Rex_WCGOP_WAOR-CA_Trawl-NonTrawl.xlsx

are on the network in ...Assessment Data\2023 Assessment Cycle\rex sole.

Please have a look and let me know if you see any issues, thanks!

--Andi

**Comment by okenk** [comment]
Looks good, thanks you!
