### ISSUE TITLE
Data request for species [replace with your species]

### ISSUE THREAD

**Issue by gertsevv** [pfmc-assessments/nwfscDiscard#13]
### Identify the common name(s)

Petrale sole

### Type of data needed

discard totals/rates and biological data

### Gear grouping

All gears combined (as I believe was done in previous petrale sole requests this year)

### Areas

coastwide (all states combined, unlike previously we requested CA and OR-WA areas separately)

### Length bins for discard compositions

12-62, with 2 cm bin width

### Additional information

This request is for coastwide petrale sole data, because we we are exploring coastwide fleet in addition to fleets divided into north and south.

### Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?

- [X] I agree that I have clearance

**Comment by chantelwetzel-noaa** [comment]
The data has been processed and posted to the network.
